### ISSUE TITLE
The plugin doesn't work for me and also prevents from showing the command pallete

### ISSUE THREAD

**Issue by The-Eighth-Man** [agathauy/wikilinks-to-mdlinks-obsidian#2]
The title.

**Comment by agathauy** [comment]
Hi! This should be working now that 0.9.15 has been released :D

**Comment by The-Eighth-Man** [comment]
Hi, now it works. Thank you. As a feature suggestion, in the obsidian links, we use the | for specifying the text shown, if that text could be put into the respective markdown link space, the [], it would improve the plugging much more.

**Comment by agathauy** [comment]
@The-Eighth-Man Oh I see! Didn't think about that as I don't use the syntax. Alright will most likely include this in the next update 👍

**Comment by NicoleMayer** [comment]
I download the latest version but still meet this problem...
